version: '3.4'

services:
  personalmanagementservicepoc.selfhosting:
    image: ${DOCKER_REGISTRY-}personalmanagementservicepocselfhosting
    build:
      context: .
      dockerfile: Dockerfile     
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5025:80"
      
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Mayur@123456789"
      ACCEPT_EULA: "Y"

